#!/usr/bin/env bash

snooze -v -s 1d -t $PWD/timefile

vim --headless \
  -c "TSUpdateSync" \
  -c "Lazy! sync" \
  -c "echo 'LazySync done'" \
  -c "autocmd User MasonToolsUpdateCompleted quitall!" \
  -c "echo ''" \
  -c "MasonToolsUpdate"

touch $PWD/timefile
